######################################
#              公共配置
######################################

# :::::: 项目启动端口 ::::::

server:
    port: 8080

# :::::: spring配置 ::::::

spring:
  profiles:
    active: dev # 当前生效环境
  devtools:
    restart:
      enabled: false

# :::::: tools的配置 ::::::

tools:
  #swagger-open: true #是否开启swagger (true/false)
  #kaptcha-open: false #是否开启登录时验证码 (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  multi-datasource-open: true #是否开启多数据源(true/false)
  #spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  #session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  #session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒

# :::::: mybatis-plus配置 ::::::

mybatis-plus:
  # 如果是放在src/main/java目录下
  mapper-locations: classpath*:com/company/scaffold/**/mapping/*.xml
  # 如果是放在resource目录 classpath:/mapping/*Mapper.xml
  #mapper-locations: classpath:/mapping/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.company.scaffold.*.entity
  # 通用枚举扫描，支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.company.scaffold.*.entity.enums
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    # 驼峰下划线转换
    db-column-underline: false
    # 数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置 (不在推荐使用此方式进行配置,请使用自定义bean注入)
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    # 刷新mapper 调试神器
    refresh-mapper: true
    # 逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # 自定义sql注入器 (不在推荐使用此方式进行配置,请使用自定义bean注入)
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    # 配置的缓存的全局开关
    cache-enabled: true
    # 延时加载的开关
    lazyLoadingEnabled: true
    # 开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    multipleResultSetsEnabled: true
    # 打印sql语句,调试用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---

######################################
#            dev 开发环境配置
######################################

# :::::: 开发环境时 spring 配置 ::::::
spring:
  profiles: dev
  # 默认数据源
  datasource:
    datasource-name: default
    url: jdbc:mysql://localhost:3306/tistools?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root123098
    filters: log4j,wall,mergeStat


# :::::: 多数据源,性能监控开关 ::::::

tools:
  # 开启mybatis-plus的性能监控插件
  mybatis-performance-open: true
  multi-datasource:
    # 多数据源名称
    datasource-name: otherDataSource
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root123098

# :::::: 日志输出、级别配置 ::::::
logging:
  level.root: info
  level.org.tis.tools: debug
  level.com.company.scaffold: debug
  path: logs/
  file: scaffold.log

---

######################################
#            pro 生产环境配置
######################################

spring:
  profiles: pro
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/tools?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root123
    filters: log4j,wall,mergeStat

tools:
  # 开启mybatis-plus的性能监控插件
  mybatis-performance-open: false

# :::::: 日志输出、级别配置 ::::::
logging:
  level.root: error
  level.org.tis.tools: error
  path: logs/
  file: scaffold.log
